### ISSUE TITLE
Code for generating circular plot

### ISSUE THREAD

**Issue by ahy1221** [pachterlab/NYMP_2018#1]
Hi, 
I am going through the code for replicating some figures of the paper.
If I understand right, it seems that the code here is only for generating the ROC plot (Supplementary Figure 2).
However, I am still not really understand how to identify DTU and DTE from the result of logistic regression fit.
As far as I understand, it will need to calculate an effect size for "direction of change". This effect size is used for plotting the  directed arrows on the cirular plot.  And then we need to observe the direction of the arrows to identify DTU of DTE.
Is that right ? I am wondering that whether I can get more details about that.
Thanks in advance!
Yao

**Comment by lynnyi** [comment]
Hi Yao,

Thanks for the question.  Yes you are correct in that you can obtain the 'direction of change,' and you can get that the direction of change from the coefficients from the logistic regression model. The vector of coefficients returned by glm (see https://www.rdocumentation.org/packages/stats/versions/3.4.3/topics/glm) indicates whether a gene is DTU or DGE. If all coefficients are positive, the overall gene expression is increasing. If all coefficients are negative, the overall gene expression is decreasing. If there is a mixture of positive and negative coefficients, the gene is undergoing DTU.

Best,
Lynn
