### ISSUE TITLE
Questions about downloading TRAPNELL data from conquer database

### ISSUE THREAD

**Issue by bsun0802** [pachterlab/NYMP_2018#2]
Hi,

I'm trying to go through the code in TRAPNELL_LOGR, but I can't find the dataset you described in conquer database. 

Instead of yours "222 serum- induced primary myoblasts over a time course of 0, 24 and 48 hours."
There are two dataset by Trapnell, one is 84 cells, and another is 288 cells. I'm trying to use the 288 cells dataset, and it is myoblasts over time 0, 24 and 48 hours. But all have the same cell type, Human Skeletal Muscle Myoblasts (HSMM). 

So I can't get two labels for cells. Did I miss something? How should I get the labels like _myogenic precursors_ v.s. _differentiating myoblasts_. 

Thank you!

**Comment by vasilisNt** [comment]
Hi! The labels are provided in the HSMMSingleCell library (https://bioconductor.org/packages/release/data/experiment/html/HSMMSingleCell.html).
Here is how to match the cells from conquer to the labels from HSMM:

```
library(MultiAssayExperiment)
library(SummarizedExperiment)
d <- readRDS("GSE52529-GPL16791.rds")
# cts <- assays(experiments(d)[["gene"]])[["count_lstpm"]] 
tpms <- assays(experiments(d)[["tx"]])[["TPM"]]

phn <- colData(d)
colnames(tpms)<-phn[,"title"]
titles<-colnames(tpms)
for (i in c(1:length(titles))){
  titles[i] = substr(titles[i], 6,15)
}

colnames(tpms)<-titles

library(HSMMSingleCell)
data("HSMM_expr_matrix")
data("HSMM_sample_sheet")

cellskeep=colnames(HSMM_expr_matrix)

cell_labels=HSMM_sample_sheet$State
cell_ptime=HSMM_sample_sheet$Pseudotime

cellskeep=cellskeep[c(1:222)]
cell_labels=cell_labels[c(1:222)]
cell_ptime=cell_ptime[c(1:222)]

tpms_final<-tpms[,cellskeep]

#write output
write.csv(cell_ptime, file = "trap_ptime222.csv")
write.csv(cell_labels, file = "trap_labels222.csv")
write.csv(tpms_final, file = "trap_tpms222.csv")
```

**Comment by bsun0802** [comment]
Thanks a lot!

A little comment that substr is vectorized, so this loop 

`for (i in c(1:length(titles))){
  titles[i] = substr(titles[i], 6,15)
}`

coule be re-factored as 

`titles <- substr(titles, 6, 15)`
