### ISSUE TITLE
Mapping Ensembl transcript IDs to CD45 isoforms

### ISSUE THREAD

**Issue by ilyakorsunsky** [pachterlab/NYMP_2018#3]
Thanks for the great insight that you can identify CD45RA and CD45RO isoforms from 10X! Do you happen to have a map of transcript IDs to isoforms for this gene? I have not been able to figure that part out on my own.

**Comment by lynnyi** [comment]
Hi, if you look at our supplementary figure that looks like this:


This figure lists the equivalence classes and the Ensembl transcripts they map to. Certain equivalence classes are differential for CD45 expression.  The figure before this one also shows where in the genome the differential reads pseudoalign to.

Does that answer your question?

**Comment by lynnyi** [comment]
Hi, I realize you were probably asking what transcripts do CD45RO and CD45RA correspond to. I found a description of the CD45 isoforms here:
https://www.bio-rad-antibodies.com/cd45-characterization-isoforms-structure-function-antibodies-minireview.html <https://www.bio-rad-antibodies.com/cd45-characterization-isoforms-structure-function-antibodies-minireview.html>

Best,
Lynn
