### ISSUE TITLE
Cannot find R file

### ISSUE THREAD

**Issue by mspivakov** [pachterlab/NYMP_2018#4]
There's a reference to ```source(../R/LRtx.R)```, but I couldn't locate this file. Is it in this repo?

**Comment by lynnyi** [comment]
Hi, apologies for the inconvenience -- the folder structure had some changes over time. I updated the paths in the embryogenesis  analysis. You should do a fresh pull and the code should work now.

**Comment by mspivakov** [comment]
Great, thanks!
